project:
  type: website
  output-dir: docs

website:
  title: "Süper Lig xG Analysis"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: data.qmd
        text: Data
      - href: analysis.qmd
        text: Analysis

format:
  html:
    theme: cosmo
    toc: true
