project:
  type: website
  output-dir: docs  # Bu satır çok kritik, çıktıları docs klasörüne atar

website:
  title: "Süper Lig xG Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: data.qmd
        text: Data
      - href: analysis.qmd
        text: Analysis

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
