project:
  type: website
  output-dir: docs

website:
  title: "Super Lig xG Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: data.qmd
        text: Data
      - href: analysis.qmd
        text: Analysis

format:
  html:
    toc: true
    code-fold: true